--------------------------------------------------------
--  File created - Monday-November-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CITYSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."CITYSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COUNTRYSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."COUNTRYSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CURRANCYSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."CURRANCYSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CUSTOMERSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."CUSTOMERSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYMANTSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."PAYMANTSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERMISSIONSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."PERMISSIONSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REMITTENCESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."REMITTENCESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."ROLESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STATESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."STATESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STATUSSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."STATUSSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REMITTANCE"."USERSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."CITY" 
   (	"CITYID" NUMBER(*,0), 
	"CITYNAME" VARCHAR2(30 BYTE), 
	"COUNTRYID" NUMBER(*,0), 
	"STATEID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."COUNTRY" 
   (	"COUNTRYID" NUMBER(*,0), 
	"COUNTRYNAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CURRANCY
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."CURRANCY" 
   (	"CURRANCYID" NUMBER(*,0), 
	"CURRANCYNAME" VARCHAR2(30 BYTE), 
	"CURRANCYCODE" VARCHAR2(30 BYTE), 
	"COUNTRYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."CUSTOMER" 
   (	"CUSTOMERID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"CONTACT" VARCHAR2(55 BYTE), 
	"EMAIL" VARCHAR2(35 BYTE), 
	"PASSWORD" VARCHAR2(25 BYTE), 
	"USERID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMANT
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."PAYMANT" 
   (	"PAYMANTID" NUMBER(*,0), 
	"PAYMANTTYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."PERMISSIONS" 
   (	"PERMISSIONID" NUMBER, 
	"PERMISSIONNAME" VARCHAR2(100 BYTE), 
	"PERMISSIONDESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REMITTENCE
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."REMITTENCE" 
   (	"REMITTENCEID" NUMBER(*,0), 
	"RECEIVERID" NUMBER(*,0), 
	"SENDERID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"PAYMANTID" NUMBER(*,0), 
	"SENDINGCURRENCYID" NUMBER(*,0), 
	"RECIEVINGCURRENCYID" NUMBER(*,0), 
	"SENDINGFROM" NUMBER(*,0), 
	"SENDINGTO" NUMBER(*,0), 
	"SENDINGAMOUNT" NUMBER(*,0), 
	"RECIEVINGAMOUNT" NUMBER(*,0), 
	"CHARGE" NUMBER(*,0), 
	"DATECREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLEPERMISSIONS
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."ROLEPERMISSIONS" 
   (	"ROLEID" NUMBER, 
	"PERMISSIONID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."ROLES" 
   (	"ROLEID" NUMBER, 
	"ROLENAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATE
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."STATE" 
   (	"STATEID" NUMBER(*,0), 
	"STATENAME" VARCHAR2(30 BYTE), 
	"COUNTRYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."STATUS" 
   (	"STATUSID" NUMBER(*,0), 
	"STATUSNAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERROLE
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."USERROLE" 
   (	"USERID" NUMBER, 
	"ROLEID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "REMITTANCE"."USERS" 
   (	"USERID" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into REMITTANCE.CITY
SET DEFINE OFF;
Insert into REMITTANCE.CITY (CITYID,CITYNAME,COUNTRYID,STATEID) values (1,'mogadishu',1,1);
REM INSERTING into REMITTANCE.COUNTRY
SET DEFINE OFF;
Insert into REMITTANCE.COUNTRY (COUNTRYID,COUNTRYNAME) values (1,'somaliaa');
Insert into REMITTANCE.COUNTRY (COUNTRYID,COUNTRYNAME) values (41,'United States');
Insert into REMITTANCE.COUNTRY (COUNTRYID,COUNTRYNAME) values (42,'United Kingdom');
REM INSERTING into REMITTANCE.CURRANCY
SET DEFINE OFF;
Insert into REMITTANCE.CURRANCY (CURRANCYID,CURRANCYNAME,CURRANCYCODE,COUNTRYID) values (1,'somali shillings','so',1);
Insert into REMITTANCE.CURRANCY (CURRANCYID,CURRANCYNAME,CURRANCYCODE,COUNTRYID) values (41,'Dollar','USD',41);
Insert into REMITTANCE.CURRANCY (CURRANCYID,CURRANCYNAME,CURRANCYCODE,COUNTRYID) values (42,'Geni','GPT',42);
REM INSERTING into REMITTANCE.CUSTOMER
SET DEFINE OFF;
Insert into REMITTANCE.CUSTOMER (CUSTOMERID,NAME,ADDRESS,CONTACT,EMAIL,PASSWORD,USERID) values (1,'Ahmed farax','hodan, mogadishu somalia','9009393','ahmed@gmail.com','mypasswod@56',1);
Insert into REMITTANCE.CUSTOMER (CUSTOMERID,NAME,ADDRESS,CONTACT,EMAIL,PASSWORD,USERID) values (26,'jamac ali','wadajir xalane','89435232','jama@gmail.com','password',1);
REM INSERTING into REMITTANCE.PAYMANT
SET DEFINE OFF;
Insert into REMITTANCE.PAYMANT (PAYMANTID,PAYMANTTYPE) values (1,'credit card');
REM INSERTING into REMITTANCE.PERMISSIONS
SET DEFINE OFF;
Insert into REMITTANCE.PERMISSIONS (PERMISSIONID,PERMISSIONNAME,PERMISSIONDESCRIPTION) values (1,'viewAllUsers','Required to View all users');
Insert into REMITTANCE.PERMISSIONS (PERMISSIONID,PERMISSIONNAME,PERMISSIONDESCRIPTION) values (2,'createUser','required to create user');
Insert into REMITTANCE.PERMISSIONS (PERMISSIONID,PERMISSIONNAME,PERMISSIONDESCRIPTION) values (3,'updateUser','required to update user');
Insert into REMITTANCE.PERMISSIONS (PERMISSIONID,PERMISSIONNAME,PERMISSIONDESCRIPTION) values (4,'deleteUser','required to delete user');
Insert into REMITTANCE.PERMISSIONS (PERMISSIONID,PERMISSIONNAME,PERMISSIONDESCRIPTION) values (5,'viewUserById','required to get one user');
REM INSERTING into REMITTANCE.REMITTENCE
SET DEFINE OFF;
Insert into REMITTANCE.REMITTENCE (REMITTENCEID,RECEIVERID,SENDERID,USERID,PAYMANTID,SENDINGCURRENCYID,RECIEVINGCURRENCYID,SENDINGFROM,SENDINGTO,SENDINGAMOUNT,RECIEVINGAMOUNT,CHARGE,DATECREATED) values (1,26,1,1,1,42,41,42,1,250,300,5,to_date('22-NOV-21','DD-MON-RR'));
REM INSERTING into REMITTANCE.ROLEPERMISSIONS
SET DEFINE OFF;
Insert into REMITTANCE.ROLEPERMISSIONS (ROLEID,PERMISSIONID) values (1,1);
Insert into REMITTANCE.ROLEPERMISSIONS (ROLEID,PERMISSIONID) values (1,2);
Insert into REMITTANCE.ROLEPERMISSIONS (ROLEID,PERMISSIONID) values (1,3);
Insert into REMITTANCE.ROLEPERMISSIONS (ROLEID,PERMISSIONID) values (1,4);
Insert into REMITTANCE.ROLEPERMISSIONS (ROLEID,PERMISSIONID) values (1,5);
REM INSERTING into REMITTANCE.ROLES
SET DEFINE OFF;
Insert into REMITTANCE.ROLES (ROLEID,ROLENAME) values (1,'admin');
Insert into REMITTANCE.ROLES (ROLEID,ROLENAME) values (2,'agent');
Insert into REMITTANCE.ROLES (ROLEID,ROLENAME) values (3,'customer');
REM INSERTING into REMITTANCE.STATE
SET DEFINE OFF;
Insert into REMITTANCE.STATE (STATEID,STATENAME,COUNTRYID) values (1,'Banadir',1);
REM INSERTING into REMITTANCE.STATUS
SET DEFINE OFF;
REM INSERTING into REMITTANCE.USERROLE
SET DEFINE OFF;
Insert into REMITTANCE.USERROLE (USERID,ROLEID) values (1,1);
REM INSERTING into REMITTANCE.USERS
SET DEFINE OFF;
Insert into REMITTANCE.USERS (USERID,EMAIL,PASSWORD,FULLNAME,ACTIVE) values (1,'abdul@gmail.com','password','abdullahi',1);
Insert into REMITTANCE.USERS (USERID,EMAIL,PASSWORD,FULLNAME,ACTIVE) values (41,'jama@gmail.com','jama1234','jamac',0);
--------------------------------------------------------
--  Constraints for Table PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."PERMISSIONS" ADD PRIMARY KEY ("PERMISSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."STATE" ADD PRIMARY KEY ("STATEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."STATE" MODIFY ("COUNTRYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."CITY" ADD PRIMARY KEY ("CITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."CITY" MODIFY ("STATEID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."CITY" MODIFY ("COUNTRYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."ROLES" ADD PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."STATUS" ADD PRIMARY KEY ("STATUSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."STATUS" MODIFY ("STATUSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REMITTENCE
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("DATECREATED" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" ADD PRIMARY KEY ("REMITTENCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("CHARGE" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("RECIEVINGAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("SENDINGAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("SENDINGTO" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("SENDINGFROM" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("RECIEVINGCURRENCYID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("SENDINGCURRENCYID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("PAYMANTID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("SENDERID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("RECEIVERID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."REMITTENCE" MODIFY ("REMITTENCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."COUNTRY" ADD PRIMARY KEY ("COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMANT
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."PAYMANT" ADD PRIMARY KEY ("PAYMANTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."PAYMANT" MODIFY ("PAYMANTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."CUSTOMER" ADD PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."CUSTOMER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."CUSTOMER" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."CUSTOMER" MODIFY ("ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURRANCY
--------------------------------------------------------

  ALTER TABLE "REMITTANCE"."CURRANCY" ADD PRIMARY KEY ("CURRANCYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REMITTANCE"."CURRANCY" MODIFY ("COUNTRYID" NOT NULL ENABLE);
  ALTER TABLE "REMITTANCE"."CURRANCY" MODIFY ("CURRANCYCODE" NOT NULL ENABLE);
